//
// Generated file, do not edit! Created by opp_msgtool 6.3 from src/TaskMessages.msg.
//

#ifndef __UAVSWARMTA_TASKMESSAGES_M_H
#define __UAVSWARMTA_TASKMESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace uavswarmta {

class TaskNotification;
class TaskBid;
class TaskAssignment;
class TaskCompletion;
class TaskDropNotification;

}  // namespace uavswarmta

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace uavswarmta {

/**
 * Class generated from <tt>src/TaskMessages.msg:14</tt> by opp_msgtool.
 * <pre>
 * // 1. MAIN NODE -> DRONES: Notifies the swarm that a new task exists
 * class TaskNotification extends inet::FieldsChunk
 * {
 *     int taskId;               // Unique ID
 *     double targetX;           // X coordinate
 *     double targetY;           // Y coordinate
 *     int priority;             // Priority level (1, 2, or 3)
 *     int requiredDrones;       // How many drones are needed to complete it
 *     double duration;          // How long the task takes to complete once they arrive (in seconds)
 * }
 * </pre>
 */
class TaskNotification : public ::inet::FieldsChunk
{
  protected:
    int taskId = 0;
    double targetX = 0;
    double targetY = 0;
    int priority = 0;
    int requiredDrones = 0;
    double duration = 0;

  private:
    void copy(const TaskNotification& other);

  protected:
    bool operator==(const TaskNotification&) = delete;

  public:
    TaskNotification();
    TaskNotification(const TaskNotification& other);
    virtual ~TaskNotification();
    TaskNotification& operator=(const TaskNotification& other);
    virtual TaskNotification *dup() const override {return new TaskNotification(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual double getTargetX() const;
    virtual void setTargetX(double targetX);

    virtual double getTargetY() const;
    virtual void setTargetY(double targetY);

    virtual int getPriority() const;
    virtual void setPriority(int priority);

    virtual int getRequiredDrones() const;
    virtual void setRequiredDrones(int requiredDrones);

    virtual double getDuration() const;
    virtual void setDuration(double duration);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskNotification& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskNotification& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/TaskMessages.msg:24</tt> by opp_msgtool.
 * <pre>
 * // 2. DRONES -> MAIN NODE: A drone's auction bid for a specific task
 * class TaskBid extends inet::FieldsChunk
 * {
 *     int taskId;               // The task they are bidding on
 *     int droneId;              // The ID of the drone making the bid
 *     double bidValue;          // The calculated bid (could be distance, remaining energy, etc.)
 * }
 * </pre>
 */
class TaskBid : public ::inet::FieldsChunk
{
  protected:
    int taskId = 0;
    int droneId = 0;
    double bidValue = 0;

  private:
    void copy(const TaskBid& other);

  protected:
    bool operator==(const TaskBid&) = delete;

  public:
    TaskBid();
    TaskBid(const TaskBid& other);
    virtual ~TaskBid();
    TaskBid& operator=(const TaskBid& other);
    virtual TaskBid *dup() const override {return new TaskBid(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);

    virtual double getBidValue() const;
    virtual void setBidValue(double bidValue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskBid& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskBid& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/TaskMessages.msg:31</tt> by opp_msgtool.
 * <pre>
 * // 3. MAIN NODE -> DRONES: The final assignment of who won the auction
 * class TaskAssignment extends inet::FieldsChunk
 * {
 *     int taskId;               // The task being assigned
 *     int assignedDroneIds[];   // Dynamic array containing the IDs of all winning drones
 * }
 * </pre>
 */
class TaskAssignment : public ::inet::FieldsChunk
{
  protected:
    int taskId = 0;
    int *assignedDroneIds = nullptr;
    size_t assignedDroneIds_arraysize = 0;

  private:
    void copy(const TaskAssignment& other);

  protected:
    bool operator==(const TaskAssignment&) = delete;

  public:
    TaskAssignment();
    TaskAssignment(const TaskAssignment& other);
    virtual ~TaskAssignment();
    TaskAssignment& operator=(const TaskAssignment& other);
    virtual TaskAssignment *dup() const override {return new TaskAssignment(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual void setAssignedDroneIdsArraySize(size_t size);
    virtual size_t getAssignedDroneIdsArraySize() const;
    virtual int getAssignedDroneIds(size_t k) const;
    virtual void setAssignedDroneIds(size_t k, int assignedDroneIds);
    virtual void insertAssignedDroneIds(size_t k, int assignedDroneIds);
    [[deprecated]] void insertAssignedDroneIds(int assignedDroneIds) {appendAssignedDroneIds(assignedDroneIds);}
    virtual void appendAssignedDroneIds(int assignedDroneIds);
    virtual void eraseAssignedDroneIds(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskAssignment& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskAssignment& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/TaskMessages.msg:37</tt> by opp_msgtool.
 * <pre>
 * // DRONE -> MAIN NODE: Task is fully finished
 * class TaskCompletion extends inet::FieldsChunk
 * {
 *     int taskId;
 *     int droneId;
 * }
 * </pre>
 */
class TaskCompletion : public ::inet::FieldsChunk
{
  protected:
    int taskId = 0;
    int droneId = 0;

  private:
    void copy(const TaskCompletion& other);

  protected:
    bool operator==(const TaskCompletion&) = delete;

  public:
    TaskCompletion();
    TaskCompletion(const TaskCompletion& other);
    virtual ~TaskCompletion();
    TaskCompletion& operator=(const TaskCompletion& other);
    virtual TaskCompletion *dup() const override {return new TaskCompletion(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual int getDroneId() const;
    virtual void setDroneId(int droneId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskCompletion& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskCompletion& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/TaskMessages.msg:43</tt> by opp_msgtool.
 * <pre>
 * // DRONE -> MAIN NODE & PEER DRONES: Task is dropped before completion
 * class TaskDropNotification extends inet::FieldsChunk
 * {
 *     int taskId;
 *     int droppingDroneId;
 *     double remainingDuration; // So the Main Node knows how much time is left
 * }
 * </pre>
 */
class TaskDropNotification : public ::inet::FieldsChunk
{
  protected:
    int taskId = 0;
    int droppingDroneId = 0;
    double remainingDuration = 0;

  private:
    void copy(const TaskDropNotification& other);

  protected:
    bool operator==(const TaskDropNotification&) = delete;

  public:
    TaskDropNotification();
    TaskDropNotification(const TaskDropNotification& other);
    virtual ~TaskDropNotification();
    TaskDropNotification& operator=(const TaskDropNotification& other);
    virtual TaskDropNotification *dup() const override {return new TaskDropNotification(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual int getDroppingDroneId() const;
    virtual void setDroppingDroneId(int droppingDroneId);

    virtual double getRemainingDuration() const;
    virtual void setRemainingDuration(double remainingDuration);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskDropNotification& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskDropNotification& obj) {obj.parsimUnpack(b);}


}  // namespace uavswarmta


namespace omnetpp {

template<> inline uavswarmta::TaskNotification *fromAnyPtr(any_ptr ptr) { return check_and_cast<uavswarmta::TaskNotification*>(ptr.get<cObject>()); }
template<> inline uavswarmta::TaskBid *fromAnyPtr(any_ptr ptr) { return check_and_cast<uavswarmta::TaskBid*>(ptr.get<cObject>()); }
template<> inline uavswarmta::TaskAssignment *fromAnyPtr(any_ptr ptr) { return check_and_cast<uavswarmta::TaskAssignment*>(ptr.get<cObject>()); }
template<> inline uavswarmta::TaskCompletion *fromAnyPtr(any_ptr ptr) { return check_and_cast<uavswarmta::TaskCompletion*>(ptr.get<cObject>()); }
template<> inline uavswarmta::TaskDropNotification *fromAnyPtr(any_ptr ptr) { return check_and_cast<uavswarmta::TaskDropNotification*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __UAVSWARMTA_TASKMESSAGES_M_H
